env:
  DOCKER_HUB_REPO: 'forumone/gesso'

# Consolidate the common configuration for reuse across multiple steps.
definitions:
  # Configure some default step values.
  step-defaults: &step-defaults
    timeout_in_minutes: 15
  matrix-setup: &matrix-setup
    setup:
      php:
        - "8.2"
        - "8.1"
        - "8.0"
      node_version:
        - "16"
        - "18"
        - "14"
      gesso_version:
        - "3"
        - "4"
        - "5"
    adjustments:
      - with:
          php: "8.2"
          gesso: "3"
        skip: true
      - with:
          php: "8.2"
          gesso: "4"
        skip: true
  linux-distro-choice: &linux-distro-choice
    - "if [[ {{matrix.gesso_version}} == 5 ]]; then LINUX_DISTRO=debian; else LINUX_DISTRO=alpine; fi"
  docker-build: &docker-build
    - "docker build -f Dockerfile-$$LINUX_DISTRO -t $DOCKER_HUB_REPO:{{matrix.gesso_version}}-node-v{{matrix.node_version}}-php-{{matrix.php}} --build-arg PHP_VERSION={{matrix.php}} --build-arg NODE_VERSION={{matrix.node_version}} ."
  docker-push: &docker-push
    - "docker push $DOCKER_HUB_REPO:{{matrix.gesso_version}}-node-v{{matrix.node_version}}-php-{{matrix.php}}"
  queues:
    # Docker-based tasks should run in the Docker queue.
    docker-agents: &docker-agents
      agents:
        queue: "docker-builders"
  plugins:
    seek: &seek
      seek-oss/aws-sm#v2.0.0:
        env:
          DOCKER_LOGIN_PASSWORD: buildkite/dockerhubid
    docker-login: &docker-login
      docker-login#v2.0.1:
        username: f1builder
        password-env: DOCKER_LOGIN_PASSWORD

steps:
  - label: ":pipeline: Build :php: {{matrix.gesso_version}}-node-v{{matrix.node_version}}-php-{{matrix.php}}"
    <<: *docker-agents
    concurrency_group: $BUILDKITE_PIPELINE_SLUG/docker
    concurrency: 4
    retry:
      automatic:
        - exit_status: -1
          limit: 2
    branches:
      - !main
    command:
      - *linux-distro-choice
      - *docker-build
    matrix:
      <<: *matrix-setup

  - label: ":pipeline: Deploy :php: {{matrix.gesso_version}}-node-v{{matrix.node_version}}-php-{{matrix.php}}"
    <<: *docker-agents
    concurrency_group: $BUILDKITE_PIPELINE_SLUG/docker
    concurrency: 4
    plugins:
      <<: *seek
      <<: *docker-login
    branches:
      - main
    retry:
      automatic:
        - exit_status: -1
          limit: 2
    command:
      - *linux-distro-choice
      - *docker-build
      - *docker-push
    matrix:
      <<: *matrix-setup
