env:
  DOCKER_HUB_REPO: 'forumone/gesso'

# Consolidate the common configuration for reuse across multiple steps.
definitions:
  # Configure some default step values.
  step-defaults: &step-defaults
    timeout_in_minutes: 15
  matrix-setup: &matrix-setup
    setup:
      php:
        - "7.4"
        - "8.0"
      node_version:
        - "16"
        - "14"
        - "12"
        - "10"
      gesso_version:
        - "4"
        - "3"
  docker-build: &docker-build
    - "docker build -t $DOCKER_HUB_REPO:{{matrix.gesso_version}}-node-v{{matrix.node_version}}-php-{{matrix.php}} --build-arg PHP_VERSION={{matrix.php}} --build-arg NODE_VERSION=$(buildkite-agent meta-data get node_specific_version) ."
  docker-push: &docker-push
    - "docker push $DOCKER_HUB_REPO:{{matrix.gesso_version}}-node-v{{matrix.node_version}}-php-{{matrix.php}}"
  queues:
    # Docker-based tasks should run in the Docker queue.
    docker-agents: &docker-agents
      agents:
        queue: "docker-builders"
  plugins:
    seek: &seek
      seek-oss/aws-sm#v2.0.0:
        env:
          DOCKER_LOGIN_PASSWORD: buildkite/dockerhubid
    docker-login: &docker-login
      docker-login#v2.0.1:
        username: f1builder
        password-env: DOCKER_LOGIN_PASSWORD

steps:
  - label: "Get node version"
    command: |
      if [ {{matrix.node_version}} == 16 ]; then
        buildkite-agent meta-data set "node_specific_version" "16.18.0"
      fi;
      if [ {{matrix.node_version}} == 14 ]; then
        buildkite-agent meta-data set "node_specific_version" "14.21.0"
      fi;
      if [ {{matrix.node_version}} == 12 ]; then
        buildkite-agent meta-data set "node_specific_version" "12.22.12"
      fi;
      if [ {{matrix.node_version}} == 10 ]; then
        buildkite-agent meta-data set "node_specific_version" "10.24.1"
      fi;

  - label: ":pipeline: Build :php: {{matrix.gesso_version}}-node-v{{matrix.node_version}}-php-{{matrix.php}}"
    <<: *docker-agents
    retry:
      automatic:
        - exit_status: -1
          limit: 2
    branches:
      - !master
    command:
      - *docker-build
    matrix:
      <<: *matrix-setup
  - label: ":pipeline: Deploy :php: {{matrix.gesso_version}}-node-v{{matrix.node_version}}-php-{{matrix.php}}"
    <<: *docker-agents
    plugins:
      <<: *seek
      <<: *docker-login
    branches:
      - master
    retry:
      automatic:
        - exit_status: -1
          limit: 2
    command:
      - *docker-build
      - *docker-push
    matrix:
      <<: *matrix-setup
